package br.com.vainaweb.schollsystem.enums;

public enum Curso {

    ANALISE_DE_SISTEMAS,
    SISTEMAS_DE_INFORMACAO,
    SISTEMAS_PARA_INTERNET,
    CIENCIA_DA_COMPUTACAO,
    ENGENHARIA_DA_COMPUTACAO,
    ENGENHARIA_DE_SOFTWARE,
    GESTAO_DE_TI,
    REDES_DE_COMPUTADORES,
    SEGURANCA_DA_INFORMACAO,
}
